### PR TITLE
Add CypherpunkPay

### PR DESCRIPTION
**Pull request by CypherpunkDev**
CypherpunkPay is a new self-hosted and fully-featured Bitcoin donations and payments processor with unique focus on the simplicity for the accepting party - a single piece, no dependencies, easy install, instant-on, minimal hardware requirements. It may be the only realistic and maintained alternative to BTCPay Server, hence I propose it as a second item on the list.

### CODE REVIEW

**Comment by CypherpunkDev** [comment]
A gentle reminder. Thanks!

**Comment by CypherpunkDev** [comment]
Once again, a gentle reminder to merge :-)

**Review by alexk111 — CHANGES_REQUESTED** [review]
Congrats on making an open-source Bitcoin processor and thanks for sharing the link to it! As it's a new processor, could you move it to the end of the *Self-Hosted Bitcoin Payment Processors* list.

**Comment by CypherpunkDev** [comment]
Of course, done.

**Review by alexk111 — APPROVED** [review]
🙏

**Pull request merged**
