### PR TITLE
Add BitcartCC

### PR DESCRIPTION
**Pull request by MrNaif2018**

### CODE REVIEW

**Comment by MrNaif2018** [comment]
Hi @alexk111! Could you please review and/or merge my PR?

**Comment by MrNaif2018** [comment]
Done. I have put it there because I saw for example PR #3 which did the same. Moved it.

**Comment by alexk111** [comment]
Thank you for adding (and making) another open-source solution! 🙏

> I have put it there because I saw for example PR #3 which did the same

The list was restructured since then: divided into hosted and self-hosted processors and sorted by the time items have been added.

**Comment by MrNaif2018** [comment]
Thank you too! Will continue improving my solution (:

**Pull request merged**
