### PR TITLE
Add NOWPayments payment gateway

### PR DESCRIPTION
**Pull request by NowPaymentsIO**
Hello, would be great if we can be added to your list.

### CODE REVIEW

**Comment by NowPaymentsIO** [comment]
@alexk111 
Hello, can you merge our pr, please?

**Comment by alexk111** [comment]
Hi,

Thanks for the PR.

1. `Directly to Your Wallet = Yes`. However in the `how it works` on your website:

> Customers sends crypto to our deposit address

Could you clarify who owns the private keys for the deposit address?

2. `Requirements = No`, and in FAQ:

> KYC/AML procedure

The requirements field should include this, as well as any other procedures required, and under which circumstances they apply.

**Comment by alexk111** [comment]
@NowPaymentsIO ping

**Comment by alexk111** [comment]
Added https://github.com/alexk111/awesome-bitcoin-payment-processors/commit/139fdae2b3a18450ccf2e686e4da6996dceb70f5

**Pull request closed without merging**
