### PR TITLE
Add Payscrypt

### PR DESCRIPTION
**Pull request by adieu**
This commit adds a new payment processor I'm currently working on called Payscrypt.

### CODE REVIEW

**Comment by alexk111** [comment]
Thanks for adding Payscrypt. Could you fix something:
free -> No fees
yes -> YES

Also you mentioned that merchants get funds directly to their wallets, not through intermediate wallets controlled by the processor. Could you provide more details on how Payscrypt's "Generate Payment Address" step works?

**Comment by adieu** [comment]
Thank you for your reply. I've made changes accordingly.

We ask the user to provide the XPUB key derived from the mnemonic code so that we could generate payment address without knowing the secret key. The payment goes directly to user's wallet where he could send out to other addresses using hardware token or other protections.

**Comment by alexk111** [comment]
Awesome, thanks!

**Comment by dades1350** [comment]
لطفا به من کمک کنید برای دریافت بیتکوین

**Pull request merged**
